import Link from 'next/link';
import {BarChart3,CheckCircle2,ClipboardList,CloudDownload,Plus} from 'lucide-react';
import {readImports} from '@/lib/import-store';
import {readReviews} from '@/lib/review-store';

export const dynamic='force-dynamic';
const when=(value:unknown)=>{const date=new Date(String(value||''));return Number.isNaN(date.getTime())?'时间未知':new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Shanghai'}).format(date)};

export default async function Matches(){
  const [rawGames,reviews]=await Promise.all([readImports(),readReviews()]);const games=rawGames.sort((a:any,b:any)=>new Date(b.playedAt||0).getTime()-new Date(a.playedAt||0).getTime());const reviewMap=new Map(reviews.map(review=>[review.gameId,review]));const reviewed=games.filter((game:any)=>reviewMap.has(String(game.gameId))).length;const average=reviews.length?Math.round(reviews.reduce((sum,item)=>sum+item.average,0)/reviews.length):null;const weakness=Object.entries(reviews.reduce<Record<string,number>>((result,item)=>({...result,[item.weakest]:(result[item.weakest]||0)+1}),{})).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';
  return <div className="mx-auto max-w-6xl p-5 md:p-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">训练样本与历史复盘</p><h1 className="mt-2 text-3xl font-black">对局记录</h1><p className="mt-2 text-white/45">已复盘对局可以随时重新查看和修改，统计会同步更新。</p></div><div className="flex gap-2"><Link className="button-secondary" href="/sync"><CloudDownload size={16}/>同步战绩</Link><Link className="button" href="/matches/new"><Plus size={16}/>手动记录</Link></div></div>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><div className="card p-5"><div className="flex items-center gap-2 text-white/40"><ClipboardList size={16}/>复盘完成率</div><b className="mt-2 block text-3xl">{games.length?Math.round(reviewed/games.length*100):0}%</b><span className="text-xs text-white/35">{reviewed} / {games.length} 局</span></div><div className="card p-5"><div className="flex items-center gap-2 text-white/40"><BarChart3 size={16}/>复盘平均分</div><b className="mt-2 block text-3xl">{average??'—'}</b><span className="text-xs text-white/35">基于 {reviews.length} 份复盘</span></div><div className="card p-5"><div className="flex items-center gap-2 text-white/40"><CheckCircle2 size={16}/>最常见短板</div><b className="mt-2 block text-2xl text-gold">{weakness}</b><span className="text-xs text-white/35">按最低评分维度统计</span></div></section>
    <div className="card mt-4 overflow-hidden">{games.length===0?<div className="p-12 text-center text-white/40">暂无已同步对局</div>:games.map((game:any)=>{const review=reviewMap.get(String(game.gameId));return <div key={game.gameId} className="grid gap-4 border-b border-white/5 p-5 last:border-0 md:grid-cols-[1.1fr_.7fr_1.2fr_.8fr_auto] md:items-center"><div><b>{game.champion}</b><p className="mt-1 text-xs text-white/35">{when(game.playedAt)}</p></div><div><span className={game.win?'text-mint':'text-rose-400'}>{game.win?'胜利':'失败'}</span><p className="mt-1 text-xs text-white/40">{game.kills} / {game.deaths} / {game.assists}</p></div><div className="text-sm text-white/45">{game.cs} CS · {game.duration?`${Math.floor(Number(game.duration)/60)} 分钟`:'时长未知'}</div><div>{review?<><span className="rounded-full bg-mint/10 px-2.5 py-1 text-xs text-mint">已复盘 · {review.average} 分</span><p className="mt-2 text-xs text-white/35">短板：{review.weakest}</p></>:<span className="rounded-full bg-white/5 px-2.5 py-1 text-xs text-white/35">待复盘</span>}</div><Link href={`/matches/new?gameId=${encodeURIComponent(game.gameId)}`} className={review?'button-secondary':'button'}>{review?'查看 / 编辑':'开始复盘'}</Link></div>})}</div>
  </div>
}
