"use client";
import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Check,CheckCircle2,Circle,LoaderCircle,Save} from 'lucide-react';
import {knowledgeModules,roleMeta} from '@/lib/knowledge-data';

type Progress=Record<string,{completed:boolean;note:string;updatedAt:string}>;

export default function Knowledge(){
  const [role,setRole]=useState('MID');const [progress,setProgress]=useState<Progress>({});const [notes,setNotes]=useState<Record<string,string>>({});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState('');const [message,setMessage]=useState('');
  useEffect(()=>{fetch('/api/knowledge',{cache:'no-store'}).then(response=>response.json()).then((data:Progress)=>{setProgress(data);setNotes(Object.fromEntries(Object.entries(data).map(([id,value])=>[id,value.note||''])))}).finally(()=>setLoading(false))},[]);
  const modules=useMemo(()=>knowledgeModules.filter(item=>item.role===role),[role]);
  const totalDone=knowledgeModules.filter(item=>progress[item.id]?.completed).length;
  const update=async(id:string,change:{completed?:boolean;note?:string})=>{setSaving(id);setMessage('');try{const response=await fetch('/api/knowledge',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({id,...change})});const value=await response.json();if(!response.ok)throw new Error(value.error);setProgress(current=>({...current,[id]:value}));setNotes(current=>({...current,[id]:value.note||''}));setMessage(change.note!==undefined?'笔记已保存。':'学习进度已更新。')}catch(error:any){setMessage(error.message||'保存失败')}finally{setSaving('')}};
  return <div className="mx-auto max-w-6xl p-5 md:p-9">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">五位置决策系统</p><h1 className="mt-2 text-3xl font-black">知识框架</h1><p className="mt-2 text-white/45">每个模块都包含一条对局规则、执行检查和你的个人笔记。</p></div><div className="card px-4 py-3 text-right"><div className="text-xs text-white/35">总掌握进度</div><b className="text-xl text-mint">{totalDone} / {knowledgeModules.length}</b></div></div>
    <div className="mt-7 grid grid-cols-2 gap-2 md:grid-cols-5">{roleMeta.map(item=>{const count=knowledgeModules.filter(module=>module.role===item.id&&progress[module.id]?.completed).length;const total=knowledgeModules.filter(module=>module.role===item.id).length;return <button key={item.id} onClick={()=>setRole(item.id)} className={`rounded-2xl border p-4 text-left transition ${role===item.id?'border-mint/40 bg-mint/[.08]':'border-white/10 bg-white/[.025] hover:bg-white/[.05]'}`}><div className={`h-1.5 w-8 rounded-full ${item.color}`}/><b className="mt-3 block">{item.name}</b><span className="mt-1 block text-xs text-white/35">{count} / {total} 已掌握</span><div className="mt-3 h-1 rounded-full bg-white/10"><div className="h-full rounded-full bg-mint" style={{width:`${total?count/total*100:0}%`}}/></div></button>})}</div>
    {message&&<div className={`mt-4 rounded-xl px-4 py-3 text-sm ${message.includes('失败')?'bg-rose-400/10 text-rose-300':'bg-mint/10 text-mint'}`}>{message}</div>}
    {loading?<div className="mt-12 flex justify-center text-white/35"><LoaderCircle className="animate-spin"/></div>:<div className="mt-6 grid gap-4 lg:grid-cols-2">{modules.map((module,index)=>{const done=Boolean(progress[module.id]?.completed);return <article key={module.id} className={`card p-5 ${done?'border-mint/25':''}`}><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${done?'bg-mint/10 text-mint':'bg-white/5 text-white/30'}`}>{done?<Check size={19}/>:<span className="text-sm font-black">{index+1}</span>}</div><div><span className="text-xs text-mint">{module.topic}</span><h2 className="mt-1 text-lg font-bold">{module.title}</h2></div></div><button disabled={saving===module.id} onClick={()=>update(module.id,{completed:!done})} className={`shrink-0 rounded-xl border px-3 py-2 text-xs transition ${done?'border-mint/30 bg-mint/10 text-mint':'border-white/10 bg-white/[.03] text-white/45 hover:bg-white/[.07]'}`}>{saving===module.id?<LoaderCircle className="animate-spin" size={15}/>:done?<span className="flex items-center gap-1.5"><CheckCircle2 size={14}/>已掌握</span>:<span className="flex items-center gap-1.5"><Circle size={14}/>标记掌握</span>}</button></div><div className="mt-5 rounded-xl border border-white/[.07] bg-white/[.025] p-4"><div className="text-xs font-bold text-gold">对局规则</div><p className="mt-2 text-sm leading-6 text-white/65">{module.rule}</p></div><div className="mt-4"><div className="text-xs font-bold text-white/35">执行前检查</div><ul className="mt-2 space-y-2">{module.checks.map(check=><li key={check} className="flex gap-2 text-sm text-white/50"><CheckCircle2 className="mt-0.5 shrink-0 text-mint/70" size={15}/>{check}</li>)}</ul></div><details className="mt-5 border-t border-white/10 pt-4" open={Boolean(notes[module.id])}><summary className="cursor-pointer text-sm text-white/45 hover:text-white/70">我的理解与实战笔记</summary><textarea rows={3} className="mt-3 w-full" value={notes[module.id]||''} onChange={event=>setNotes(current=>({...current,[module.id]:event.target.value}))} placeholder="记录这个规则在你的英雄或分段中如何执行…"/><div className="mt-2 flex justify-end"><button disabled={saving===module.id} onClick={()=>update(module.id,{note:notes[module.id]||''})} className="button-secondary"><Save size={14}/>保存笔记</button></div></details></article>})}</div>}
    <div className="card mt-4 p-6"><div className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-gold/10 text-gold"><BookOpen/></div><div><h2 className="font-bold">通用核心：资源交换四问</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/45">对方得到什么？我们能在另一侧拿什么？这次交换的兵线成本是多少？交换结束后，下一处资源谁先到？每次地图决策先回答这四问。</p></div></div></div>
  </div>
}
