"use client";
import {FormEvent,useEffect,useState} from 'react';
import {ChevronDown,LoaderCircle,Pencil,Plus,Save,Shield,Swords,Trash2,X} from 'lucide-react';

type Champion={id:string;champion:string;role:string;tier:string;notes:string;matchup:string;games:number;wins:number;winRate:number|null};
type Draft={champion:string;role:string;tier:string;notes:string;matchup:string};
const empty:Draft={champion:'',role:'中路',tier:'主力',notes:'',matchup:''};
const roles=['上路','打野','中路','下路','辅助'];const tiers=['主力','备选','练习'];

export default function Champions(){
  const [items,setItems]=useState<Champion[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [showForm,setShowForm]=useState(false);const [editing,setEditing]=useState<string|null>(null);const [draft,setDraft]=useState<Draft>(empty);const [message,setMessage]=useState('');
  const load=async()=>{setLoading(true);try{const response=await fetch('/api/champions',{cache:'no-store'});setItems(await response.json())}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setMessage('');try{const response=await fetch('/api/champions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});const data=await response.json();if(!response.ok)throw new Error(data.error);setItems(data);setDraft(empty);setShowForm(false);setMessage('英雄已加入英雄池，战绩统计会自动关联。')}catch(error:any){setMessage(error.message||'保存失败')}finally{setSaving(false)}};
  const beginEdit=(item:Champion)=>{setEditing(item.id);setDraft({champion:item.champion,role:item.role,tier:item.tier,notes:item.notes,matchup:item.matchup});setMessage('')};
  const saveEdit=async()=>{if(!editing)return;setSaving(true);try{const response=await fetch('/api/champions',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:editing,...draft})});const data=await response.json();if(!response.ok)throw new Error(data.error);setItems(data);setEditing(null);setDraft(empty);setMessage('英雄计划已更新。')}catch(error:any){setMessage(error.message||'更新失败')}finally{setSaving(false)}};
  const remove=async(item:Champion)=>{if(!window.confirm(`从英雄池移除 ${item.champion}？`))return;const response=await fetch(`/api/champions?id=${encodeURIComponent(item.id)}`,{method:'DELETE'});const data=await response.json();if(response.ok)setItems(data);else setMessage(data.error||'删除失败')};
  const field=(key:keyof Draft,value:string)=>setDraft(current=>({...current,[key]:value}));
  return <div className="mx-auto max-w-6xl p-5 md:p-9">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">稳定上分系统</p><h1 className="mt-2 text-3xl font-black">英雄池与对位</h1><p className="mt-2 text-white/45">固定少量英雄，战绩由国服同步自动统计；对位计划由你持续沉淀。</p></div><button onClick={()=>{setShowForm(!showForm);setEditing(null);setDraft(empty);setMessage('')}} className={showForm?'button-secondary':'button'}>{showForm?<X size={16}/>:<Plus size={16}/>} {showForm?'取消':'添加英雄'}</button></div>
    {showForm&&<form onSubmit={submit} className="card mt-6 p-5 md:p-6"><div className="flex items-center gap-2"><Swords className="text-mint" size={19}/><h2 className="font-bold">添加到英雄池</h2></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm text-white/55">英雄名称<input autoFocus value={draft.champion} onChange={e=>field('champion',e.target.value)} placeholder="例如：奥莉安娜" required/></label><label className="grid gap-2 text-sm text-white/55">位置<select value={draft.role} onChange={e=>field('role',e.target.value)}>{roles.map(role=><option key={role}>{role}</option>)}</select></label><label className="grid gap-2 text-sm text-white/55">英雄池定位<select value={draft.tier} onChange={e=>field('tier',e.target.value)}>{tiers.map(tier=><option key={tier}>{tier}</option>)}</select></label></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm text-white/55">使用计划<textarea rows={3} value={draft.notes} onChange={e=>field('notes',e.target.value)} placeholder="强势期、选用场景、核心打法…"/></label><label className="grid gap-2 text-sm text-white/55">对位备忘<textarea rows={3} value={draft.matchup} onChange={e=>field('matchup',e.target.value)} placeholder="例如：对劫保留 E，6 级后控制兵线位置…"/></label></div><div className="mt-5 flex justify-end"><button disabled={saving} className="button disabled:opacity-60">{saving?<LoaderCircle className="animate-spin" size={16}/>:<Plus size={16}/>}保存英雄</button></div></form>}
    {message&&<div className={`mt-4 rounded-xl px-4 py-3 text-sm ${message.includes('失败')||message.includes('填写')?'bg-rose-400/10 text-rose-300':'bg-mint/10 text-mint'}`}>{message}</div>}
    {loading?<div className="mt-12 flex justify-center text-white/35"><LoaderCircle className="animate-spin"/></div>:items.length===0?<div className="card mt-8 p-12 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-white/5 text-white/30"><Swords/></div><h2 className="mt-4 font-bold">英雄池还是空的</h2><p className="muted mt-2">添加第一个主力英雄，已同步战绩会自动匹配局数与胜率。</p><button onClick={()=>setShowForm(true)} className="button mt-5"><Plus size={16}/>添加英雄</button></div>:<div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item=>{
      const active=editing===item.id;return <article key={item.id} className="card overflow-hidden"><div className="border-b border-white/10 bg-gradient-to-br from-mint/[.08] to-transparent p-5"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/10"><Swords className="text-white/70" size={20}/></div><span className={`rounded-full px-2.5 py-1 text-xs ${item.tier==='主力'?'bg-mint/10 text-mint':item.tier==='备选'?'bg-gold/10 text-gold':'bg-white/5 text-white/45'}`}>{item.tier}</span></div><h2 className="mt-5 text-xl font-black">{item.champion}</h2><p className="mt-1 text-sm text-white/40">{item.role}</p><div className="mt-5 grid grid-cols-3 gap-3 border-t border-white/10 pt-4 text-center"><div><div className="text-xs text-white/30">同步场次</div><b>{item.games}</b></div><div><div className="text-xs text-white/30">胜场</div><b>{item.wins}</b></div><div><div className="text-xs text-white/30">胜率</div><b>{item.winRate===null?'—':`${item.winRate}%`}</b></div></div></div>
      {active?<div className="space-y-4 p-5"><div className="grid grid-cols-2 gap-3"><label className="grid gap-1.5 text-xs text-white/45">位置<select value={draft.role} onChange={e=>field('role',e.target.value)}>{roles.map(role=><option key={role}>{role}</option>)}</select></label><label className="grid gap-1.5 text-xs text-white/45">定位<select value={draft.tier} onChange={e=>field('tier',e.target.value)}>{tiers.map(tier=><option key={tier}>{tier}</option>)}</select></label></div><label className="grid gap-1.5 text-xs text-white/45">使用计划<textarea rows={3} value={draft.notes} onChange={e=>field('notes',e.target.value)}/></label><label className="grid gap-1.5 text-xs text-white/45">对位备忘<textarea rows={4} value={draft.matchup} onChange={e=>field('matchup',e.target.value)}/></label><div className="flex gap-2"><button onClick={saveEdit} disabled={saving} className="button flex-1"><Save size={15}/>保存</button><button onClick={()=>setEditing(null)} className="button-secondary"><X size={15}/></button></div></div>:<div className="p-5"><div><div className="text-xs text-white/30">使用计划</div><p className="mt-2 min-h-10 text-sm leading-6 text-white/55">{item.notes||'尚未填写，建议记录选用场景和核心打法。'}</p></div><details className="mt-4 rounded-xl bg-white/[.035] p-3"><summary className="flex cursor-pointer list-none items-center justify-between text-sm text-white/60">对位备忘<ChevronDown size={15}/></summary><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-white/45">{item.matchup||'尚未记录具体对位。'}</p></details><div className="mt-5 flex gap-2"><button onClick={()=>beginEdit(item)} className="button-secondary flex-1"><Pencil size={14}/>编辑计划</button><button aria-label={`删除 ${item.champion}`} onClick={()=>remove(item)} className="button-secondary text-rose-300"><Trash2 size={14}/></button></div></div>}
    </article>})}</div>}
    <div className="card mt-4 p-5"><div className="flex gap-3"><Shield className="mt-0.5 shrink-0 text-gold" size={19}/><div><h2 className="font-bold">英雄池建议</h2><p className="mt-2 text-sm leading-6 text-white/45">主位置保留 2–3 个主力英雄：一个稳定盲选、一个弥补阵容伤害类型、一个应对特殊对位。同步场次只统计名称完全匹配的真实战绩。</p></div></div></div>
  </div>
}
