import Link from 'next/link';
import {ArrowRight,CloudDownload,Flame,Plus,Target,Trophy} from 'lucide-react';
import {readImports} from '@/lib/import-store';

export const dynamic='force-dynamic';
const roleNames:Record<string,string>={TOP:'上路',JUNGLE:'打野',MIDDLE:'中路',MID:'中路',BOTTOM:'下路',ADC:'下路',UTILITY:'辅助',SUPPORT:'辅助',BOTTOM_CARRY:'下路',BOTTOM_SUPPORT:'辅助'};
const roleName=(raw:unknown)=>{const value=String(raw||'').toUpperCase();return roleNames[value]||roleNames[value.split('_')[0]]||(value.includes('SUPPORT')?'辅助':value.includes('CARRY')?'下路':'未知位置')};
const when=(value:unknown)=>{const date=new Date(String(value||''));return Number.isNaN(date.getTime())?'时间未知':new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Shanghai'}).format(date)};

export default async function Dashboard(){
  const all=(await readImports()).sort((a:any,b:any)=>new Date(b.playedAt||0).getTime()-new Date(a.playedAt||0).getTime());const games=all.slice(0,20);const recent=games.slice(0,5);const wins=games.filter((game:any)=>game.win).length;const winRate=games.length?Math.round(wins/games.length*100):0;const weekAgo=Date.now()-7*24*60*60*1000;const weekGames=games.filter((game:any)=>new Date(game.playedAt||0).getTime()>=weekAgo).length;
  const firstResult=Boolean(games[0]?.win);let streak=0;for(const game of games){if(Boolean(game.win)!==firstResult)break;streak++}const totalDeaths=games.reduce((sum:number,game:any)=>sum+Number(game.deaths||0),0);const avgKda=games.length?((games.reduce((sum:number,game:any)=>sum+Number(game.kills||0)+Number(game.assists||0),0))/Math.max(1,totalDeaths)).toFixed(2):'—';const minutes=games.reduce((sum:number,game:any)=>sum+Number(game.duration||0),0)/60;const csPerMinute=minutes?(games.reduce((sum:number,game:any)=>sum+Number(game.cs||0),0)/minutes).toFixed(1):'—';
  return <div className="mx-auto max-w-7xl p-5 md:p-9"><header className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">真实战绩控制台</p><h1 className="mt-2 text-3xl font-black md:text-4xl">晚上好，召唤师</h1><p className="mt-2 text-white/45">当前统计来自国服客户端同步，不再使用示例对局。</p></div><div className="flex gap-2"><Link className="button-secondary" href="/sync"><CloudDownload size={17}/>同步战绩</Link><Link className="button" href="/matches/new"><Plus size={17}/>记录一局</Link></div></header>
    <section className="grid gap-4 sm:grid-cols-3"><div className="card p-5"><div className="muted">近 {games.length} 局胜率</div><div className="mt-2 flex items-end gap-2"><b className="text-4xl">{games.length?`${winRate}%`:'—'}</b>{games.length>0&&<span className="mb-1 text-sm text-white/35">{wins} 胜 {games.length-wins} 负</span>}</div></div><div className="card p-5"><div className="muted">最近 7 天对局</div><div className="mt-2 flex items-end gap-2"><b className="text-4xl">{weekGames}</b><span className="mb-1 text-sm text-white/35">局</span></div></div><div className="card p-5"><div className="muted">当前连续结果</div><div className="mt-2 flex items-center gap-3"><b className={`text-4xl ${games.length&&firstResult?'text-mint':games.length?'text-rose-300':''}`}>{games.length?`${streak}${firstResult?'连胜':'连败'}`:'—'}</b>{games.length&&firstResult?<Flame className="text-orange-400"/>:null}</div></div></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-[1.05fr_.95fr]"><div className="card p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">下一局唯一目标</p><h2 className="mt-2 text-xl font-bold">资源刷新前，先处理兵线</h2></div><Target className="text-mint"/></div><p className="mt-3 max-w-xl text-sm leading-6 text-white/45">小龙或先锋刷新前 45 秒观察边线。先处理一波兵线，再移动到河道抢位置。</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-lg bg-mint/10 px-3 py-1.5 text-xs text-mint">专项：兵线 × 地图意识</span><Link href="/training" className="rounded-lg bg-white/5 px-3 py-1.5 text-xs text-white/45 hover:text-white">进入训练中心 →</Link></div></div><div className="card p-5"><p className="eyebrow">近 20 局真实表现</p><div className="mt-5 grid grid-cols-2 gap-4"><div className="rounded-xl bg-white/[.035] p-4"><div className="text-xs text-white/35">平均 KDA</div><b className="mt-1 block text-2xl">{avgKda}</b></div><div className="rounded-xl bg-white/[.035] p-4"><div className="text-xs text-white/35">平均 CS / 分钟</div><b className="mt-1 block text-2xl">{csPerMinute}</b></div></div><div className="mt-5 flex flex-wrap gap-1.5">{games.length?games.slice().reverse().map((game:any)=><span key={game.gameId} title={`${game.champion} · ${game.win?'胜利':'失败'}`} className={`h-3 flex-1 rounded-sm ${game.win?'bg-mint':'bg-rose-400/70'}`}/>):<span className="text-sm text-white/35">同步战绩后显示胜负走势。</span>}</div></div></section>
    <section className="card mt-4 overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="eyebrow">最近对局</p><h2 className="mt-1 text-lg font-bold">国服同步样本</h2></div><Link href="/matches" className="text-sm text-white/45 hover:text-white">查看全部</Link></div>{recent.length===0?<div className="p-10 text-center"><Trophy className="mx-auto text-white/20"/><p className="mt-3 text-white/40">还没有真实对局，先同步国服战绩。</p><Link href="/sync" className="button mt-5"><CloudDownload size={16}/>开始同步</Link></div>:recent.map((game:any)=><div key={game.gameId} className="grid gap-3 border-b border-white/5 p-5 last:border-0 sm:grid-cols-[1.1fr_.8fr_1.4fr_auto] sm:items-center"><div><b>{game.champion||'未知英雄'}</b><div className="text-xs text-white/35">{roleName(game.role)} · {when(game.playedAt)}</div></div><div><span className={game.win?'text-mint':'text-rose-400'}>{game.win?'胜利':'失败'}</span><div className="text-xs text-white/45">{game.kills} / {game.deaths} / {game.assists}</div></div><div className="text-sm text-white/45">{Number(game.cs||0)} CS · {game.duration?`${Math.floor(Number(game.duration)/60)} 分钟`:'时长未知'}</div><Link href={`/matches/new?gameId=${encodeURIComponent(game.gameId)}`} className="flex items-center gap-2 text-sm text-mint">复盘<ArrowRight size={14}/></Link></div>)}</section>
  </div>
}
