import {NextResponse} from 'next/server';
import {readTrainingTasks,writeTrainingTasks,type TrainingTask} from '@/lib/training-store';
import {readReviews} from '@/lib/review-store';

const clean=(value:unknown,max=500)=>String(value??'').trim().slice(0,max);
const visible=(tasks:TrainingTask[])=>tasks.filter(task=>task.status!=='ARCHIVED').sort((a,b)=>Number(b.selected)-Number(a.selected)||b.updatedAt.localeCompare(a.updatedAt));
async function result(tasks:TrainingTask[]){const reviews=await readReviews();return {tasks:visible(tasks),stats:{reviews:reviews.length,average:reviews.length?Math.round(reviews.reduce((sum,item)=>sum+item.average,0)/reviews.length):null,completed:tasks.filter(item=>item.status==='COMPLETED').length}}}

export async function GET(){return NextResponse.json(await result(await readTrainingTasks()))}
export async function POST(request:Request){const body=await request.json();const title=clean(body.title,100);const dimension=clean(body.dimension,40)||'自定义';const successRule=clean(body.successRule);const targetCount=Math.max(1,Math.min(20,Number(body.targetCount)||3));if(!title||!successRule)return NextResponse.json({error:'请填写任务名称和完成标准'},{status:400});const tasks=await readTrainingTasks();const now=new Date().toISOString();tasks.unshift({id:crypto.randomUUID(),title,dimension,successRule,targetCount,completedCount:0,status:'ACTIVE',selected:!tasks.some(item=>item.selected&&item.status==='ACTIVE'),createdAt:now,updatedAt:now});await writeTrainingTasks(tasks);return NextResponse.json(await result(tasks),{status:201})}
export async function PATCH(request:Request){const body=await request.json();const tasks=await readTrainingTasks();const task=tasks.find(item=>item.id===clean(body.id,100));if(!task)return NextResponse.json({error:'训练任务不存在'},{status:404});const now=new Date().toISOString();if(body.action==='select'){for(const item of tasks)item.selected=item.id===task.id&&item.status==='ACTIVE'}else if(body.action==='increment'||body.action==='decrement'){const delta=body.action==='increment'?1:-1;task.completedCount=Math.max(0,Math.min(task.targetCount,task.completedCount+delta));task.status=task.completedCount>=task.targetCount?'COMPLETED':'ACTIVE';if(task.status==='COMPLETED')task.selected=false}else if(body.action==='complete'){task.completedCount=task.targetCount;task.status='COMPLETED';task.selected=false}else if(body.action==='reopen'){task.status='ACTIVE';task.completedCount=Math.min(task.completedCount,task.targetCount-1)}else if(body.action==='archive'){task.status='ARCHIVED';task.selected=false}else return NextResponse.json({error:'无法识别的操作'},{status:400});task.updatedAt=now;if(!tasks.some(item=>item.selected&&item.status==='ACTIVE')){const next=tasks.find(item=>item.status==='ACTIVE');if(next)next.selected=true}await writeTrainingTasks(tasks);return NextResponse.json(await result(tasks))}
