import https from 'node:https';
import http from 'node:http';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {existsSync,readFileSync} from 'node:fs';
const exec=promisify(execFile);
const target=process.env.RIFT_MASTERY_URL||'http://127.0.0.1:3000';
const syncToken=process.env.RIFT_SYNC_TOKEN||'local-dev';
function getArg(command,name){const match=command.match(new RegExp(`--${name}=([^ "']+)|--${name} ([^ "']+)`));return match?.[1]||match?.[2]}
function fromLockfile(){for(const drive of ['C','D','E','F','G']){const file=`${drive}:\\WeGameApps\\英雄联盟\\LeagueClient\\lockfile`;if(!existsSync(file))continue;try{const parts=readFileSync(file,'utf8').trim().split(':');if(parts.length>=5&&parts[2]&&parts[3])return {port:Number(parts[2]),auth:parts[3]}}catch{}}}
async function findClient(){const script=`$all=Get-CimInstance Win32_Process | Where-Object {$_.Name -eq 'LeagueClientUx.exe'}; $p=$all | Where-Object {$_.CommandLine} | Select-Object -First 1; if($p){'COMMAND='+$p.CommandLine}; if($all){'RUNNING=1'}`;const {stdout}=await exec('powershell.exe',['-NoProfile','-Command',script],{windowsHide:true});const commandLine=stdout.split(/\r?\n/).find(line=>line.startsWith('COMMAND='))?.slice(8)||'';const port=getArg(commandLine,'app-port');const auth=getArg(commandLine,'remoting-auth-token');if(port&&auth)return {port:Number(port),auth};const lock=fromLockfile();if(lock)return lock;if(stdout.includes('RUNNING=1'))throw new Error('检测到客户端正在运行，但 Windows 阻止读取连接参数。请右键以管理员身份打开终端，再运行 node scripts/lcu-sync.mjs');throw new Error('没有检测到已登录的英雄联盟客户端')}
function lcu(path,client){return new Promise((resolve,reject)=>{const req=https.request({hostname:'127.0.0.1',port:client.port,path,method:'GET',rejectUnauthorized:false,headers:{Authorization:`Basic ${Buffer.from(`riot:${client.auth}`).toString('base64')}`}},res=>{let body='';res.on('data',d=>body+=d);res.on('end',()=>{if(res.statusCode>=400)return reject(new Error(`客户端接口返回 ${res.statusCode}`));try{resolve(JSON.parse(body))}catch{reject(new Error('客户端返回了无法识别的数据'))}})});req.on('error',reject);req.end()})}
function post(path,data){const url=new URL(path,target);return new Promise((resolve,reject)=>{const body=JSON.stringify(data);const request=http.request(url,{method:'POST',headers:{'content-type':'application/json','content-length':Buffer.byteLength(body),'x-sync-token':syncToken}},res=>{let text='';res.on('data',d=>text+=d);res.on('end',()=>res.statusCode>=400?reject(new Error(`Web 接收失败 ${res.statusCode}: ${text}`)):resolve(JSON.parse(text)))});request.on('error',reject);request.end(body)})}
function samePlayer(player,me){return [player?.puuid,player?.accountId,player?.currentAccountId,player?.summonerId,String(player?.summonerId)].filter(Boolean).some(id=>[me.puuid,me.accountId,me.summonerId,String(me.summonerId)].filter(Boolean).includes(id))}
function normalize(game,me,champions){const identities=game.participantIdentities||[];const identity=identities.find(i=>samePlayer(i.player,me));const participants=game.participants||[];const participant=participants.find(p=>p.participantId===identity?.participantId)||participants.find(p=>samePlayer(p,me))||participants.find(p=>p.isMe);const stats=participant?.stats||participant||{};const timeline=participant?.timeline||{};const championId=participant?.championId;const lane=participant?.teamPosition||participant?.individualPosition||timeline.lane||participant?.lane||'UNKNOWN';const position=timeline.role&&timeline.role!=='SOLO'?`${lane}_${timeline.role}`:lane;const opponent=participants.find(p=>p.teamId!==participant?.teamId&&((p.timeline?.lane&&p.timeline.lane===timeline.lane)||(p.teamPosition&&p.teamPosition===participant?.teamPosition)));const opponentId=opponent?.championId;return {gameId:String(game.gameId||game.id),playedAt:new Date(game.gameCreation||game.gameCreationDate||Date.now()).toISOString(),duration:game.gameDuration||game.gameLength||0,queueId:game.queueId||game.queueType,champion:participant?.championName||champions.get(Number(championId))||championId||'未知英雄',championId:championId||null,opponent:opponent?.championName||champions.get(Number(opponentId))||opponentId||'',role:position,win:Boolean(stats.win??participant?.win),kills:Number(stats.kills||0),deaths:Number(stats.deaths||0),assists:Number(stats.assists||0),cs:Number(stats.totalMinionsKilled||0)+Number(stats.neutralMinionsKilled||0),gold:Number(stats.goldEarned||0),items:[0,1,2,3,4,5,6].map(i=>stats[`item${i}`]).filter(Boolean)}}
async function main(){console.log('正在连接国服 LOL 客户端…');const client=await findClient();const me=await lcu('/lol-summoner/v1/current-summoner',client);const lookup=me.puuid||me.accountId;const [history,championList]=await Promise.all([lcu(`/lol-match-history/v1/products/lol/${encodeURIComponent(lookup)}/matches?begIndex=0&endIndex=19`,client),lcu('/lol-game-data/assets/v1/champion-summary.json',client).catch(()=>[])]);const raw=history.games?.games||history.games||history.matches||[];const champions=new Map((championList||[]).map(c=>[Number(c.id),c.name]));console.log(`已找到 ${raw.length} 局，正在读取每局详细数据…`);const details=await Promise.all(raw.map(async summary=>{const gameId=summary.gameId||summary.id;try{return await lcu(`/lol-match-history/v1/games/${gameId}`,client)}catch{return summary}}));const games=details.map(g=>normalize(g,me,champions));const result=await post('/api/lcu/import',{summoner:{displayName:me.displayName||me.gameName||'召唤师',puuid:me.puuid,level:me.summonerLevel},games});console.log(`同步完成：新增 ${result.added} 局，更新 ${result.updated||0} 局。`)}
main().catch(error=>{console.error(`同步失败：${error.message}`);process.exitCode=1});
