"use client";
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Check,Target} from 'lucide-react';

const dims=['对线','兵线','地图意识','资源交换','团战','英雄熟练度','装备理解','阵容理解','稳定性'];
const roleNames:Record<string,string>={TOP:'上路',JUNGLE:'打野',MIDDLE:'中路',MID:'中路',BOTTOM:'下路',ADC:'下路',UTILITY:'辅助',SUPPORT:'辅助',BOTTOM_CARRY:'下路',BOTTOM_SUPPORT:'辅助'};
const formatDuration=(seconds:number)=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;
type Form={result:string;role:string;champion:string;opponent:string;kills:string;deaths:string;assists:string;duration:string};
const empty:Form={result:'胜利',role:'中路',champion:'',opponent:'',kills:'',deaths:'',assists:'',duration:''};
const reviewGroups=[{key:'death',title:'第一次可控死亡',options:['压线无视野','换血判断失误','贪兵/镀层','支援晚到','团战站位','操作失误','无可控死亡']},{key:'macro',title:'最大决策问题',options:['兵线没处理','资源硬接团','该打却撤退','无收益游走','回城时机差','转线错误','决策基本正确']},{key:'next',title:'下局优先修正',options:['多看小地图','提前处理兵线','少一次贪心','先确认人数','明确团战职责','控制第一次死亡']}];

export default function NewMatch(){
  const [step,setStep]=useState(1);const [form,setForm]=useState<Form>(empty);const [imported,setImported]=useState(false);
  const [quick,setQuick]=useState<Record<string,string>>({});
  const [scores,setScores]=useState<Record<string,number>>(Object.fromEntries(dims.map(d=>[d,3])));
  const average=useMemo(()=>Math.round(Object.values(scores).reduce((a,b)=>a+b,0)/dims.length*20),[scores]);
  useEffect(()=>{const gameId=new URLSearchParams(window.location.search).get('gameId');if(!gameId)return;fetch('/api/lcu/import',{cache:'no-store'}).then(r=>r.json()).then((games:any[])=>{const game=games.find(g=>String(g.gameId)===gameId);if(!game)return;const rawRole=String(game.role||'').toUpperCase();const mapped=roleNames[rawRole]||roleNames[rawRole.split('_')[0]]||(rawRole.includes('SUPPORT')?'辅助':rawRole.includes('CARRY')?'下路':'中路');setForm({result:game.win?'胜利':'失败',role:mapped,champion:String(game.champion||''),opponent:String(game.opponent||''),kills:String(game.kills??''),deaths:String(game.deaths??''),assists:String(game.assists??''),duration:game.duration?formatDuration(Number(game.duration)):''});setImported(true)})},[]);
  const update=(key:keyof Form,value:string)=>setForm(current=>({...current,[key]:value}));
  return <div className="mx-auto max-w-4xl p-5 md:p-9">
    <Link href="/sync" className="mb-7 inline-flex items-center gap-2 text-sm text-white/40 hover:text-white"><ArrowLeft size={16}/>返回同步列表</Link>
    <div className="mb-8"><p className="eyebrow">新建训练样本</p><div className="flex flex-wrap items-center gap-3"><h1 className="mt-2 text-3xl font-black">记录一局排位</h1>{imported&&<span className="mt-2 rounded-full bg-mint/10 px-3 py-1 text-xs text-mint">已自动填入战绩</span>}</div><div className="mt-6 flex gap-2">{[1,2,3].map(n=><div key={n} className={`h-1 flex-1 rounded-full ${n<=step?'bg-mint':'bg-white/10'}`}/>)}</div><div className="mt-2 flex justify-between text-xs text-white/35"><span>对局信息</span><span>关键复盘</span><span>训练结论</span></div></div>
    {step===1&&<div className="card p-5 md:p-7"><h2 className="text-xl font-bold">发生了什么？</h2>{imported&&<p className="mt-2 text-sm text-mint/80">以下客观数据来自国服客户端，你可以按需修正。</p>}<div className="mt-6 grid gap-5 sm:grid-cols-2">
      <label className="grid gap-2 text-sm text-white/60">结果<select value={form.result} onChange={e=>update('result',e.target.value)}><option>胜利</option><option>失败</option></select></label>
      <label className="grid gap-2 text-sm text-white/60">位置<select value={form.role} onChange={e=>update('role',e.target.value)}>{['中路','上路','打野','下路','辅助'].map(r=><option key={r}>{r}</option>)}</select></label>
      <label className="grid gap-2 text-sm text-white/60">使用英雄<input value={form.champion} onChange={e=>update('champion',e.target.value)} placeholder="例如：奥莉安娜"/></label>
      <label className="grid gap-2 text-sm text-white/60">对位英雄<input value={form.opponent} onChange={e=>update('opponent',e.target.value)} placeholder="客户端无法判断时可手动补充"/></label>
      <label className="grid gap-2 text-sm text-white/60">K / D / A<div className="grid grid-cols-3 gap-2"><input value={form.kills} onChange={e=>update('kills',e.target.value)} type="number" placeholder="击杀"/><input value={form.deaths} onChange={e=>update('deaths',e.target.value)} type="number" placeholder="死亡"/><input value={form.assists} onChange={e=>update('assists',e.target.value)} type="number" placeholder="助攻"/></div></label>
      <label className="grid gap-2 text-sm text-white/60">游戏时长<input value={form.duration} onChange={e=>update('duration',e.target.value)} placeholder="例如：31:24"/></label>
    </div></div>}
    {step===2&&<div className="space-y-4"><div className="card p-5 md:p-7"><div className="flex items-end justify-between gap-3"><div><h2 className="text-xl font-bold">30 秒能力评分</h2><p className="muted mt-2">3 分代表符合当前水平，只调整明显偏高或偏低的项目。</p></div><span className="rounded-lg bg-mint/10 px-3 py-1.5 text-xs text-mint">默认全选 3</span></div><div className="mt-6 space-y-5">{dims.map(d=><div key={d} className="grid items-center gap-2 sm:grid-cols-[110px_1fr_24px]"><span className="text-sm">{d}</span><input aria-label={d} type="range" min="1" max="5" value={scores[d]} onChange={e=>setScores({...scores,[d]:Number(e.target.value)})} className="h-1 accent-[#56d6b3]"/><b className="text-mint">{scores[d]}</b></div>)}</div></div><div className="card p-5 md:p-7"><div className="flex items-center justify-between"><h2 className="font-bold">快速归因</h2><span className="text-xs text-white/30">每组点一个即可</span></div><div className="mt-5 space-y-6">{reviewGroups.map(group=><div key={group.key}><p className="mb-3 text-sm text-white/55">{group.title}</p><div className="flex flex-wrap gap-2">{group.options.map(option=><button type="button" key={option} onClick={()=>setQuick({...quick,[group.key]:option})} className={`rounded-xl border px-3 py-2 text-sm transition ${quick[group.key]===option?'border-mint/50 bg-mint/10 text-mint':'border-white/10 bg-white/[.03] text-white/45 hover:bg-white/[.07]'}`}>{option}</button>)}</div></div>)}</div><details className="mt-6 border-t border-white/10 pt-4"><summary className="cursor-pointer text-sm text-white/40 hover:text-white/70">补充一句备注（可选）</summary><textarea className="mt-3 w-full" rows={2} placeholder="只有选项无法表达时再填写…"/></details></div></div>}
    {step===3&&<div className="card p-6 md:p-8"><div className="grid h-12 w-12 place-items-center rounded-full bg-mint/10 text-mint"><Check/></div><p className="eyebrow mt-6">复盘已完成 · 综合 {average} 分</p><h2 className="mt-2 text-2xl font-black">下一局：资源刷新前先处理兵线</h2><p className="mt-3 max-w-2xl text-white/45">下一局只观察一个动作：小龙或先锋刷新前 45 秒，是否先处理兵线再靠近河道。</p><div className="mt-6 rounded-xl border border-mint/20 bg-mint/5 p-4"><div className="flex items-center gap-2 text-sm font-bold text-mint"><Target size={17}/>完成标准</div><p className="mt-2 text-sm text-white/55">3 次资源刷新中至少 2 次提前处理兵线。</p></div><Link className="button mt-6" href="/">保存并返回总览</Link></div>}
    {step<3&&<div className="mt-5 flex justify-end gap-3"><button disabled={step===1} onClick={()=>setStep(step-1)} className="button-secondary disabled:opacity-30">上一步</button><button onClick={()=>setStep(step+1)} className="button">继续<ArrowRight size={16}/></button></div>}
  </div>
}
