"use client";
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Check,LoaderCircle,Save,Target} from 'lucide-react';
import {abilityDimensions as dims} from '@/lib/review-data';

const roleNames:Record<string,string>={TOP:'上路',JUNGLE:'打野',MIDDLE:'中路',MID:'中路',BOTTOM:'下路',ADC:'下路',UTILITY:'辅助',SUPPORT:'辅助',BOTTOM_CARRY:'下路',BOTTOM_SUPPORT:'辅助'};
const formatDuration=(seconds:number)=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;
type Form={result:string;role:string;champion:string;opponent:string;kills:string;deaths:string;assists:string;duration:string};
type Saved={review:{gameId:string;average:number};analysis:{average:number;weakest:{dimension:string;value:number};goal:{title:string;rule:string}}};
const empty:Form={result:'胜利',role:'中路',champion:'',opponent:'',kills:'',deaths:'',assists:'',duration:''};
const reviewGroups=[{key:'death',title:'第一次可控死亡',options:['压线无视野','换血判断失误','贪兵/镀层','支援晚到','团战站位','操作失误','无可控死亡']},{key:'macro',title:'最大决策问题',options:['兵线没处理','资源硬接团','该打却撤退','无收益游走','回城时机差','转线错误','决策基本正确']},{key:'next',title:'下局优先修正',options:['多看小地图','提前处理兵线','少一次贪心','先确认人数','明确团战职责','控制第一次死亡']}];

export default function NewMatch(){
  const [step,setStep]=useState(1);const [gameId,setGameId]=useState('');const [form,setForm]=useState<Form>(empty);const [imported,setImported]=useState(false);const [existing,setExisting]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState<Saved|null>(null);const [quick,setQuick]=useState<Record<string,string>>({});const [note,setNote]=useState('');const [scores,setScores]=useState<Record<string,number>>(Object.fromEntries(dims.map(d=>[d,3])));
  const average=useMemo(()=>Math.round(Object.values(scores).reduce((a,b)=>a+b,0)/dims.length*20),[scores]);
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get('gameId')||'';setGameId(id);if(!id){setLoading(false);return}Promise.all([fetch('/api/lcu/import',{cache:'no-store'}).then(r=>r.json()),fetch(`/api/reviews?gameId=${encodeURIComponent(id)}`,{cache:'no-store'}).then(r=>r.json())]).then(([games,review])=>{const game=(games as any[]).find(item=>String(item.gameId)===id);if(game){const rawRole=String(game.role||'').toUpperCase();const mapped=roleNames[rawRole]||roleNames[rawRole.split('_')[0]]||(rawRole.includes('SUPPORT')?'辅助':rawRole.includes('CARRY')?'下路':'中路');setForm({result:game.win?'胜利':'失败',role:mapped,champion:String(game.champion||''),opponent:String(game.opponent||''),kills:String(game.kills??''),deaths:String(game.deaths??''),assists:String(game.assists??''),duration:game.duration?formatDuration(Number(game.duration)):''});setImported(true)}if(review){setForm(review.form);setScores(review.scores);setQuick(review.quick||{});setNote(review.note||'');setExisting(true);setStep(2)}}).catch(()=>setError('读取对局失败，请返回列表重试。')).finally(()=>setLoading(false))},[]);
  const update=(key:keyof Form,value:string)=>setForm(current=>({...current,[key]:value}));
  const save=async()=>{setSaving(true);setError('');try{const response=await fetch('/api/reviews',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({gameId,form,scores,quick,note})});const value=await response.json();if(!response.ok)throw new Error(value.error);setSaved(value);setGameId(value.review.gameId);setExisting(true);setStep(3)}catch(reason:any){setError(reason.message||'复盘保存失败')}finally{setSaving(false)}};
  if(loading)return <div className="grid min-h-[60vh] place-items-center text-white/35"><LoaderCircle className="animate-spin"/></div>;
  return <div className="mx-auto max-w-4xl p-5 md:p-9"><Link href="/matches" className="mb-7 inline-flex items-center gap-2 text-sm text-white/40 hover:text-white"><ArrowLeft size={16}/>返回对局记录</Link>
    <div className="mb-8"><p className="eyebrow">{existing?'复盘详情与编辑':'新建训练样本'}</p><div className="flex flex-wrap items-center gap-3"><h1 className="mt-2 text-3xl font-black">{existing?'查看复盘':'记录一局排位'}</h1>{imported&&<span className="mt-2 rounded-full bg-mint/10 px-3 py-1 text-xs text-mint">客观数据来自国服客户端</span>}{existing&&<span className="mt-2 rounded-full bg-gold/10 px-3 py-1 text-xs text-gold">已保存，可重新编辑</span>}</div><div className="mt-6 flex gap-2">{[1,2,3].map(n=><div key={n} className={`h-1 flex-1 rounded-full ${n<=step?'bg-mint':'bg-white/10'}`}/>)}</div><div className="mt-2 flex justify-between text-xs text-white/35"><span>对局信息</span><span>关键复盘</span><span>训练结论</span></div></div>
    {error&&<div className="mb-4 rounded-xl bg-rose-400/10 px-4 py-3 text-sm text-rose-300">{error}</div>}
    {step===1&&<div className="card p-5 md:p-7"><h2 className="text-xl font-bold">发生了什么？</h2>{imported&&<p className="mt-2 text-sm text-mint/80">以下客观数据已自动填入，你可以按需修正。</p>}<div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm text-white/60">结果<select value={form.result} onChange={e=>update('result',e.target.value)}><option>胜利</option><option>失败</option></select></label><label className="grid gap-2 text-sm text-white/60">位置<select value={form.role} onChange={e=>update('role',e.target.value)}>{['中路','上路','打野','下路','辅助'].map(r=><option key={r}>{r}</option>)}</select></label><label className="grid gap-2 text-sm text-white/60">使用英雄<input value={form.champion} onChange={e=>update('champion',e.target.value)} placeholder="例如：奥莉安娜"/></label><label className="grid gap-2 text-sm text-white/60">对位英雄<input value={form.opponent} onChange={e=>update('opponent',e.target.value)} placeholder="客户端无法判断时可手动补充"/></label><label className="grid gap-2 text-sm text-white/60">K / D / A<div className="grid grid-cols-3 gap-2"><input value={form.kills} onChange={e=>update('kills',e.target.value)} type="number" placeholder="击杀"/><input value={form.deaths} onChange={e=>update('deaths',e.target.value)} type="number" placeholder="死亡"/><input value={form.assists} onChange={e=>update('assists',e.target.value)} type="number" placeholder="助攻"/></div></label><label className="grid gap-2 text-sm text-white/60">游戏时长<input value={form.duration} onChange={e=>update('duration',e.target.value)} placeholder="例如：31:24"/></label></div></div>}
    {step===2&&<div className="space-y-4"><div className="card p-5 md:p-7"><div className="flex items-end justify-between gap-3"><div><h2 className="text-xl font-bold">30 秒能力评分</h2><p className="muted mt-2">3 分代表符合当前水平，只调整明显偏高或偏低的项目。</p></div><span className="rounded-lg bg-mint/10 px-3 py-1.5 text-xs text-mint">当前综合 {average}</span></div><div className="mt-6 space-y-5">{dims.map(d=><div key={d} className="grid items-center gap-2 sm:grid-cols-[110px_1fr_24px]"><span className="text-sm">{d}</span><input aria-label={d} type="range" min="1" max="5" value={scores[d]} onChange={e=>setScores({...scores,[d]:Number(e.target.value)})} className="h-1 accent-[#56d6b3]"/><b className="text-mint">{scores[d]}</b></div>)}</div></div><div className="card p-5 md:p-7"><div className="flex items-center justify-between"><h2 className="font-bold">快速归因</h2><span className="text-xs text-white/30">每组点一个即可</span></div><div className="mt-5 space-y-6">{reviewGroups.map(group=><div key={group.key}><p className="mb-3 text-sm text-white/55">{group.title}</p><div className="flex flex-wrap gap-2">{group.options.map(option=><button type="button" key={option} onClick={()=>setQuick({...quick,[group.key]:option})} className={`rounded-xl border px-3 py-2 text-sm transition ${quick[group.key]===option?'border-mint/50 bg-mint/10 text-mint':'border-white/10 bg-white/[.03] text-white/45 hover:bg-white/[.07]'}`}>{option}</button>)}</div></div>)}</div><details className="mt-6 border-t border-white/10 pt-4" open={Boolean(note)}><summary className="cursor-pointer text-sm text-white/40 hover:text-white/70">补充一句备注（可选）</summary><textarea value={note} onChange={event=>setNote(event.target.value)} className="mt-3 w-full" rows={3} placeholder="只有选项无法表达时再填写…"/></details></div></div>}
    {step===3&&saved&&<div className="card p-6 md:p-8"><div className="grid h-12 w-12 place-items-center rounded-full bg-mint/10 text-mint"><Check/></div><p className="eyebrow mt-6">复盘已保存 · 综合 {saved.analysis.average} 分</p><h2 className="mt-2 text-2xl font-black">下一局：{saved.analysis.goal.title}</h2><p className="mt-3 max-w-2xl text-white/45">本局最低维度是「{saved.analysis.weakest.dimension}」，已自动在训练中心生成或关联对应专项。</p><div className="mt-6 rounded-xl border border-mint/20 bg-mint/5 p-4"><div className="flex items-center gap-2 text-sm font-bold text-mint"><Target size={17}/>完成标准</div><p className="mt-2 text-sm text-white/55">{saved.analysis.goal.rule}</p></div><div className="mt-6 flex flex-wrap gap-3"><Link className="button" href="/training">去训练中心选择目标</Link><button onClick={()=>setStep(2)} className="button-secondary">继续编辑复盘</button><Link className="button-secondary" href="/matches">返回对局列表</Link></div></div>}
    {step<3&&<div className="mt-5 flex justify-end gap-3"><button disabled={step===1||saving} onClick={()=>setStep(step-1)} className="button-secondary disabled:opacity-30">上一步</button>{step===1?<button disabled={!form.champion} onClick={()=>setStep(2)} className="button disabled:opacity-40">继续<ArrowRight size={16}/></button>:<button disabled={saving} onClick={save} className="button disabled:opacity-60">{saving?<LoaderCircle className="animate-spin" size={16}/>:<Save size={16}/>} {existing?'保存更新':'保存复盘'}</button>}</div>}
  </div>
}
