"use client";
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {Archive,CheckCircle2,Circle,Clock,Focus,LoaderCircle,Minus,Play,Plus,Target,X} from 'lucide-react';

type Task={id:string;title:string;dimension:string;successRule:string;targetCount:number;completedCount:number;status:'ACTIVE'|'COMPLETED';selected:boolean;sourceReviewId?:string};
type Data={tasks:Task[];stats:{reviews:number;average:number|null;completed:number}};
const initial:Data={tasks:[],stats:{reviews:0,average:null,completed:0}};

export default function Training(){
  const [data,setData]=useState<Data>(initial);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [showForm,setShowForm]=useState(false);const [message,setMessage]=useState('');const [draft,setDraft]=useState({title:'',dimension:'兵线',successRule:'',targetCount:3});
  const load=async()=>{setLoading(true);try{setData(await fetch('/api/training',{cache:'no-store'}).then(response=>response.json()))}finally{setLoading(false)}};useEffect(()=>{load()},[]);
  const act=async(id:string,action:string)=>{setBusy(id+action);setMessage('');try{const response=await fetch('/api/training',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,action})});const value=await response.json();if(!response.ok)throw new Error(value.error);setData(value);setMessage(action==='select'?'已切换下一局训练目标。':'训练进度已更新。')}catch(error:any){setMessage(error.message||'更新失败')}finally{setBusy('')}};
  const add=async(event:FormEvent)=>{event.preventDefault();setBusy('new');try{const response=await fetch('/api/training',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)});const value=await response.json();if(!response.ok)throw new Error(value.error);setData(value);setDraft({title:'',dimension:'兵线',successRule:'',targetCount:3});setShowForm(false);setMessage('自定义训练任务已创建。')}catch(error:any){setMessage(error.message||'创建失败')}finally{setBusy('')}};
  const active=data.tasks.filter(task=>task.status==='ACTIVE');const completed=data.tasks.filter(task=>task.status==='COMPLETED');const selected=active.find(task=>task.selected);
  return <div className="mx-auto max-w-6xl p-5 md:p-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">刻意练习</p><h1 className="mt-2 text-3xl font-black">训练中心</h1><p className="mt-2 text-white/45">复盘会自动生成专项；你可以选择下一局目标并更新完成进度。</p></div><button onClick={()=>setShowForm(!showForm)} className={showForm?'button-secondary':'button'}>{showForm?<X size={16}/>:<Plus size={16}/>} {showForm?'取消':'自定义任务'}</button></div>
    {showForm&&<form onSubmit={add} className="card mt-6 p-5"><h2 className="font-bold">创建自定义专项</h2><div className="mt-4 grid gap-4 md:grid-cols-[1fr_.6fr_110px]"><label className="grid gap-2 text-sm text-white/50">任务名称<input required value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})} placeholder="例如：控制第一次可控死亡"/></label><label className="grid gap-2 text-sm text-white/50">能力维度<select value={draft.dimension} onChange={event=>setDraft({...draft,dimension:event.target.value})}>{['对线','兵线','地图意识','资源交换','团战','英雄熟练度','装备理解','阵容理解','稳定性'].map(item=><option key={item}>{item}</option>)}</select></label><label className="grid gap-2 text-sm text-white/50">目标局数<input type="number" min="1" max="20" value={draft.targetCount} onChange={event=>setDraft({...draft,targetCount:Number(event.target.value)})}/></label></div><label className="mt-4 grid gap-2 text-sm text-white/50">完成标准<input required value={draft.successRule} onChange={event=>setDraft({...draft,successRule:event.target.value})} placeholder="写成对局结束后能明确判断完成/未完成的标准"/></label><div className="mt-4 flex justify-end"><button disabled={busy==='new'} className="button">{busy==='new'?<LoaderCircle className="animate-spin" size={16}/>:<Plus size={16}/>}创建任务</button></div></form>}
    {message&&<div className={`mt-4 rounded-xl px-4 py-3 text-sm ${message.includes('失败')?'bg-rose-400/10 text-rose-300':'bg-mint/10 text-mint'}`}>{message}</div>}
    <div className="mt-8 grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><section><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">进行中的专项</h2><span className="text-xs text-white/35">一次只选择一个</span></div>{loading?<div className="card grid place-items-center p-12 text-white/30"><LoaderCircle className="animate-spin"/></div>:active.length===0?<div className="card p-10 text-center"><Focus className="mx-auto text-white/25"/><h3 className="mt-3 font-bold">还没有训练任务</h3><p className="muted mt-2">完成一局复盘后，系统会根据最低评分自动创建专项。</p><Link href="/matches" className="button mt-5">选择一局开始复盘</Link></div>:<div className="space-y-3">{active.map(task=>{const percent=Math.round(task.completedCount/task.targetCount*100);return <article key={task.id} className={`card p-5 ${task.selected?'border-mint/35 bg-mint/[.025]':''}`}><div className="flex gap-4"><button aria-label="选择任务" onClick={()=>act(task.id,'select')} className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${task.selected?'bg-mint/10 text-mint':'bg-white/5 text-white/30 hover:text-white'}`}>{task.selected?<Focus size={20}/>:<Circle size={19}/>}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="flex flex-wrap items-center gap-2"><b>{task.title}</b>{task.selected&&<span className="rounded-full bg-mint/10 px-2 py-0.5 text-[10px] text-mint">下一局目标</span>}</div><p className="mt-1 text-xs text-white/40">{task.dimension}{task.sourceReviewId?' · 来自复盘':' · 自定义'}</p></div><span className="text-xs text-white/35">{task.completedCount} / {task.targetCount} 局</span></div><p className="mt-3 text-sm leading-6 text-white/50">完成标准：{task.successRule}</p><div className="mt-4 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-mint transition-all" style={{width:`${percent}%`}}/></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><button disabled={task.selected||busy!==''} onClick={()=>act(task.id,'select')} className="button-secondary disabled:opacity-40">{task.selected?'当前已选择':'设为下一局目标'}</button><div className="flex gap-2"><button aria-label="减少进度" disabled={task.completedCount===0||busy!==''} onClick={()=>act(task.id,'decrement')} className="button-secondary px-3 disabled:opacity-30"><Minus size={15}/></button><button disabled={busy!==''} onClick={()=>act(task.id,'increment')} className="button"><CheckCircle2 size={15}/>本局做到</button><button aria-label="归档任务" disabled={busy!==''} onClick={()=>act(task.id,'archive')} className="button-secondary px-3 text-white/35"><Archive size={15}/></button></div></div></div></div></article>})}</div>}</section>
      <aside className="space-y-4"><div className="card p-5"><div className="flex items-center gap-2 text-gold"><Target size={18}/><b>下一局目标</b></div>{selected?<><h3 className="mt-4 text-lg font-bold">{selected.title}</h3><p className="mt-2 text-sm leading-6 text-white/45">{selected.successRule}</p></>:<p className="muted mt-4">从左侧选择一个进行中的专项。</p>}</div><div className="card p-5"><b>复盘统计</b><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div><strong className="text-2xl">{data.stats.reviews}</strong><div className="text-[11px] text-white/30">已复盘</div></div><div><strong className="text-2xl">{data.stats.average??'—'}</strong><div className="text-[11px] text-white/30">平均分</div></div><div><strong className="text-2xl">{data.stats.completed}</strong><div className="text-[11px] text-white/30">已完成专项</div></div></div></div><div className="card p-5"><b>训练原则</b><ul className="mt-4 space-y-4 text-sm text-white/50"><li className="flex gap-2"><CheckCircle2 className="shrink-0 text-mint" size={17}/>每局只带一个明确目标</li><li className="flex gap-2"><Clock className="shrink-0 text-mint" size={17}/>结束后 3 分钟内完成复盘</li><li className="flex gap-2"><Play className="shrink-0 text-mint" size={17}/>连续达到目标局数才算形成习惯</li></ul></div></aside></div>
    {completed.length>0&&<section className="mt-8"><h2 className="mb-4 text-lg font-bold">已完成专项</h2><div className="grid gap-3 md:grid-cols-2">{completed.map(task=><div key={task.id} className="card flex items-center gap-3 p-4"><CheckCircle2 className="shrink-0 text-mint"/><div className="min-w-0 flex-1"><b className="text-sm">{task.title}</b><p className="mt-1 text-xs text-white/35">完成 {task.targetCount} 局 · {task.dimension}</p></div><button onClick={()=>act(task.id,'reopen')} className="text-xs text-white/40 hover:text-white">重新训练</button></div>)}</div></section>}
  </div>
}
